version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # volumes:
      #   - .:/app
    ports:
      - 3000:3000
    entrypoint: ["yarn", "start"]
  cypress:
    build:
      context: cypress
      dockerfile: Dockerfile.cypress
    depends_on:
      - frontend
