version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run yarn tests
          command: yarn run test
workflows:
    test_my_app:
      jobs:
        - test
