version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    resource_class: small
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
