name: Anchore image scan

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 * * * *'

jobs:
  anchore-image-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build local container
      uses: docker/build-push-action@v2
      with:
        tags: localbuild/testimage:latest
        push: false
        load: true
    - name: Run Anchore image image
      uses: anchore/scan-action@v3
      id: anchore-scan
      with:
       image: "localbuild/testimage:latest"
       fail-build: false
    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.anchore-scan.outputs.sarif }}
