name: Anchore directory scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  anchore-directory-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Anchore directory image
      uses: anchore/scan-action@v3
      id: anchore-scan
      with:
       path: "."
       fail-build: false
