name: Image scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: build local container
      uses: docker/build-push-action@v2
      with:
        tags: localbuild/testimage:latest
        push: false
        load: true
    - name: Run Clair image scan
      uses: santander-group/clair-scan-action@eed36cec0a745465e2a58a47409ce0ea3a7cb3a5
      with:
        image: "localbuild/testimage:latest"
    - name: Run Trivy image scan
      uses: aquasecurity/trivy-action@0.0.20
      with:
        image-ref: "localbuild/testimage:latest"
        format: "table"
        exit-code: "0"
        ignore-unfixed: true
        vuln-type: os
    - name: Run Anchore directory scan
      uses: anchore/scan-action@v3
      with:
        path: "."
        acs-report-enable: false
        fail-build: false
    - name: Run Anchore image scan
      id: scan
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
        fail-build: false
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
