name: Trivy filesystem scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-filesystem-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.0.20
      with:
        scan-type: 'fs'
        ignore-unfixed: false
        format: 'table'
